# ***** Telegram TOKEN y parámetros definidos *****
TOKEN = "<YOUR TELEGRAM TOKEN>"
CHANNEL_NAME = "<YOUR TELEGRAM CHANNEL NAME>"

# ***** TIEMPO DE ACTIVIDAD DEL BOT *****
MIN_HOUR = 9
MAX_HOUR = 24
PAUSE_MINUTES = 12

# ***** Amazon API Keys y parámetros *****
AMAZON_ACCESS_KEY = "<YOUR AMAZON ACCESS KEY>"
AMAZON_SECRET_KEY = "<YOUR AMAZON SECRET KEY>"
PARTNER_TAG = "<YOUR AMAZON PARTNER TAG>"
AMAZON_HOST = "<YOUR AMAZON HOST>"
AMAZON_REGION = "<YOUR AMAZON REGION>"
